version: "3.3"
services:
  node:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    ports:
      - "480:8080"
    command: /bin/sh -c "/home/node/app/startup.sh"

